// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-PGjZliyv0xBlR28gMYT0EsSiyLQLbY',
    appId: '1:351823736744:web:3b67432ec6396921faf79d',
    messagingSenderId: '351823736744',
    projectId: 'customer-data-base-13fab',
    authDomain: 'customer-data-base-13fab.firebaseapp.com',
    databaseURL: 'https://customer-data-base-13fab-default-rtdb.firebaseio.com',
    storageBucket: 'customer-data-base-13fab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPbNK7wmjCAM-dYlF5ZgYt614aN3ss6fo',
    appId: '1:351823736744:android:2d6f49a66bfe87f0faf79d',
    messagingSenderId: '351823736744',
    projectId: 'customer-data-base-13fab',
    databaseURL: 'https://customer-data-base-13fab-default-rtdb.firebaseio.com',
    storageBucket: 'customer-data-base-13fab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNZ1nUvuWFVctz8GdlLkUDe0NF0M0_gY',
    appId: '1:351823736744:ios:eae7f0192101aeadfaf79d',
    messagingSenderId: '351823736744',
    projectId: 'customer-data-base-13fab',
    databaseURL: 'https://customer-data-base-13fab-default-rtdb.firebaseio.com',
    storageBucket: 'customer-data-base-13fab.firebasestorage.app',
    iosBundleId: 'com.example.driverApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwNZ1nUvuWFVctz8GdlLkUDe0NF0M0_gY',
    appId: '1:351823736744:ios:eae7f0192101aeadfaf79d',
    messagingSenderId: '351823736744',
    projectId: 'customer-data-base-13fab',
    databaseURL: 'https://customer-data-base-13fab-default-rtdb.firebaseio.com',
    storageBucket: 'customer-data-base-13fab.firebasestorage.app',
    iosBundleId: 'com.example.driverApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5-PGjZliyv0xBlR28gMYT0EsSiyLQLbY',
    appId: '1:351823736744:web:cb1b91897b156613faf79d',
    messagingSenderId: '351823736744',
    projectId: 'customer-data-base-13fab',
    authDomain: 'customer-data-base-13fab.firebaseapp.com',
    databaseURL: 'https://customer-data-base-13fab-default-rtdb.firebaseio.com',
    storageBucket: 'customer-data-base-13fab.firebasestorage.app',
  );
}
